"""
Note that this file was largely generated by Claude. I don't know whether that makes the code
more ore less readable, I just thought it would be nice to let you know :)
"""

import sys
import os
sys.path.insert(0, os.path.dirname(__file__))

from flask import Flask, jsonify, request, render_template
import numpy as np
import copy
import math

# ── Project imports ───────────────────────────────────────────────────────────
from farm.farm import Farm, egg_specs, max_cr, max_er, hab_capacities, vehicle_capacities
from farm.artifact import Artifact, Artifact_set, Stone, artifact_specs, stone_specs
from farm.prices import cr_prices, hab_prices, vehicle_prices, silo_price, cr_names, cr_bounds
from farm.farm import max_er
from methods import format as fmt, format_time, egg_read, read_time

# Reuse the project's own simulation logic directly
from simulation.commands import (
    State, te_numbers, te_treshholds, virtue_egg_index,
    research_available, buy, buy_all, buy_cr, buy_hab, buy_vehicle, buy_silo,
    shift as cli_shift
)
from simulation.wait import (
    wait_offline, wait_active, time_cash_away, time_cash_active, time_layed
)
from simulation.egg_simulation import simulate_egg as cli_simulate_egg

app = Flask(__name__)
app.secret_key = os.environ.get('SECRET_KEY', 'fallback-for-dev')

# ── State helpers ─────────────────────────────────────────────────────────────
def default_state():
    return {
        "egg": "curiosity",
        "te": 0,
        "se": 0,
        "pe": 0,
        "cr": [0] * 56,
        "er": [15,20,20,20,20,10,10,10,20,100,20,12,20,140,20,20,30,10,20,5,60,10],
        "silos": 1,
        "habs": [1, 0, 0, 0],
        "vehicles": [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
        "pop": 0,
        "cash": 0,
        "colleggtibles": [4]*11,
        "eggs_layed": [0.0, 0.0, 0.0, 0.0, 0.0],
        "time_elapsed": 0,
        "shifts": 0,
        "te_claimed": [0, 0, 0, 0, 0],
        "log": [],
        "artifact_set": {
            "a1": {"type": "", "level": 0, "rarity": 0, "stones": [{"type":"","level":0},{"type":"","level":0},{"type":"","level":0}]},
            "a2": {"type": "", "level": 0, "rarity": 0, "stones": [{"type":"","level":0},{"type":"","level":0},{"type":"","level":0}]},
            "a3": {"type": "", "level": 0, "rarity": 0, "stones": [{"type":"","level":0},{"type":"","level":0},{"type":"","level":0}]},
            "a4": {"type": "", "level": 0, "rarity": 0, "stones": [{"type":"","level":0},{"type":"","level":0},{"type":"","level":0}]},
        },
        "events": {"cash":1,"drone":1,"cr":1,"hab":1,"veh":1,"gift":1},
        "shifts_start": 0,
        "video_doubler": True
    }

def build_stone(s):
    if not s or s.get("type","") == "":
        return Stone()
    return Stone(type=s["type"], level=int(s["level"]))

def build_artifact(a):
    if not a or a.get("type","") == "":
        return Artifact()
    stones = a.get("stones", [{},{},{}])
    while len(stones) < 3:
        stones.append({"type":"","level":0})
    return Artifact(
        type=a["type"], level=int(a["level"]), rarity=int(a["rarity"]),
        stone1=build_stone(stones[0]),
        stone2=build_stone(stones[1]),
        stone3=build_stone(stones[2])
    )

def build_artifact_set(aset_data):
    return Artifact_set(
        a1=build_artifact(aset_data.get("a1",{})),
        a2=build_artifact(aset_data.get("a2",{})),
        a3=build_artifact(aset_data.get("a3",{})),
        a4=build_artifact(aset_data.get("a4",{})),
    )

def build_farm(d):
    """Build a Farm object from a state dict."""
    aset = build_artifact_set(d["artifact_set"])
    f = Farm(
        egg=d["egg"],
        cr=np.array(d["cr"], dtype=float),
        er=list(d["er"]),
        silos=int(d["silos"]),
        habs=list(d["habs"]),
        vehicles=list(d["vehicles"]),
        se=float(d["se"]),
        pe=int(d["pe"]),
        te=int(d["te"]),
        colleggtibles=np.array(d["colleggtibles"], dtype=float),
        pop=float(d["pop"]),
        artifact_set=aset,
        video_doubler=bool(d["video_doubler"]),
        cash=float(d["cash"])
    )
    # Apply events
    for k, v in d.get("events", {}).items():
        if k in f.event_effects:
            f.event_effects[k] = float(v)
    return f

def dict_to_state(d):
    """Convert a state dict to a CLI State object, preserving all fields."""
    f = build_farm(d)
    s = State(farm=f, time_elapsed=float(d["time_elapsed"]),
              eggs_layed=list(d["eggs_layed"]), shifts=int(d["shifts"]))
    s.te_claimed = list(d.get("te_claimed", [te_numbers(e) for e in d["eggs_layed"]]))
    return s

def state_to_dict(cli_state, d_orig):
    """Write back CLI State changes into a fresh copy of the original dict."""
    d = copy.deepcopy(d_orig)
    f = cli_state.farm
    d["egg"]          = f.egg
    d["cr"]           = f.cr.tolist() if isinstance(f.cr, np.ndarray) else list(f.cr)
    d["er"]           = list(f.er)
    d["silos"]        = int(f.silos)
    d["habs"]         = list(f.habs)
    d["vehicles"]     = list(f.vehicles)
    d["se"]           = float(f.se)
    d["pe"]           = int(f.pe)
    d["te"]           = int(f.te)
    d["colleggtibles"]= f.colleggtibles.tolist() if isinstance(f.colleggtibles, np.ndarray) else list(f.colleggtibles)
    d["pop"]          = float(f.pop)
    d["cash"]         = float(f.cash)
    d["video_doubler"]= bool(f.video_doubler)
    d["time_elapsed"] = float(cli_state.time_elapsed)
    d["eggs_layed"]   = [float(e) for e in cli_state.eggs_layed]
    d["shifts"]       = int(cli_state.shifts)
    d["te_claimed"]   = [int(x) for x in cli_state.te_claimed]
    # Serialize artifact_set back
    def stone_dict(st):
        return {"type": st.type, "level": int(st.level)}
    def art_dict(a):
        return {"type": a.type, "level": int(a.level), "rarity": int(a.rarity),
                "stones": [stone_dict(a.stone1), stone_dict(a.stone2), stone_dict(a.stone3)]}
    d["artifact_set"] = {
        "a1": art_dict(f.artf.a1), "a2": art_dict(f.artf.a2),
        "a3": art_dict(f.artf.a3), "a4": art_dict(f.artf.a4),
    }
    return d

def serialize(d):
    """Ensure all numpy types are plain Python for JSON."""
    s = copy.deepcopy(d)
    for key in ("cr","colleggtibles","eggs_layed","vehicles","habs","er","te_claimed"):
        if key in s and hasattr(s[key], "tolist"):
            s[key] = s[key].tolist()
    return s

def add_log(d, action, detail=""):
    d.setdefault("log", [])
    d["log"].append({"action": action, "detail": detail, "time": _fmt_time(d["time_elapsed"])})
    if len(d["log"]) > 100:
        d["log"] = d["log"][-100:]

def _fmt_time(t):
    return format_time(float(t))

# ── Stats ─────────────────────────────────────────────────────────────────────

def get_farm_stats(d):
    try:
        f = build_farm(d)
        eggs  = d["eggs_layed"]
        te_cl = d.get("te_claimed", [0]*5)
        egg_names = ["curiosity","kindness","resilience","humility","integrity"]
        virtue_eggs_info = []
        for i, en in enumerate(egg_names):
            tn       = te_numbers(eggs[i])
            claimed  = int(te_cl[i])
            pending  = max(0, tn - claimed)
            next_th  = te_treshholds(tn + 1)
            prev_th  = te_treshholds(tn)
            progress = (eggs[i] - prev_th) / (next_th - prev_th) if next_th > prev_th else 1.0
            virtue_eggs_info.append({
                "name": en, "layed": fmt(eggs[i]),
                "next": fmt(next_th),
                "te_total": tn,
                "te_claimed": claimed,
                "te_pending": pending,
                "progress": float(min(max(progress, 0.0), 1.0))
            })
        te_pending_total = sum(v["te_pending"] for v in virtue_eggs_info)
        # Time to next TE on current egg
        egg_idx   = virtue_egg_index.get(d["egg"], 0)
        cur_layed = float(d["eggs_layed"][egg_idx])
        next_th   = te_treshholds(te_numbers(cur_layed) + 1)
        eggs_needed = max(0.0, next_th - cur_layed)
        cli = dict_to_state(d)
        try:
            t_next_te = time_layed(cli, eggs_needed) if eggs_needed > 0 else 0
        except Exception:
            t_next_te = 0
        return {
            "egg": d["egg"],
            "cash": fmt(f.cash),
            "time": _fmt_time(d["time_elapsed"]),
            "pop":  fmt(f.pop),
            "hab_size": fmt(f.hab_size),
            "shipping": fmt(f.max_shipping * 60),
            "laying":   fmt(f.laying_chick * f.pop * 60),
            "earnings_away":   fmt(f.earnings_away()),
            "earnings_active": fmt(f.earnings_active()),
            "te":         int(d["te"]),
            "te_pending": te_pending_total,
            "time_to_next_te": _fmt_time(t_next_te) if t_next_te > 0 else "—",
            "shifts": int(d["shifts"]),
            "shifts_start": int(d.get("shifts_start", 0)),
            "video_doubler": bool(d.get("video_doubler", True)),
            "habs":    list(d["habs"]),
            "vehicles":list(d["vehicles"])[:f.max_vehicle_number],
            "max_vehicle_number": int(f.max_vehicle_number),
            "silos":  int(d["silos"]),
            "max_away_time": _fmt_time(f.max_away_time * 60),
            "ihr_away":    fmt(f.ihr_away * 60),
            "max_rcb": round(float(f.max_rcb), 2),
            "virtue_eggs": virtue_eggs_info,
            "eb": str(fmt(float(f.eb))) + "%",
            "farm_value": fmt(f.farm_value()),
        }
    except Exception as e:
        import traceback; traceback.print_exc()
        return {"error": str(e)}

# ── Routes ────────────────────────────────────────────────────────────────────
@app.route('/')
def index():
    return render_template('index.html')

@app.route('/api/state/init', methods=['POST'])
def init_state():
    data = request.json or {}
    state = default_state()
    for key in ["egg","te","se","pe","cr","er","silos","habs","vehicles","pop","cash",
                "colleggtibles","video_doubler","eggs_layed","artifact_set","events"]:
        if key in data:
            state[key] = data[key]
    state["log"] = data.get("log", [])
    state["time_elapsed"] = 0
    state["shifts"] = int(data.get("shifts", 0))
    state["shifts_start"] = int(data.get("shifts", 0))  # current run starts here
    # Only recalculate te_claimed if not explicitly provided (fresh start from real game values)
    if "te_claimed" in data:
        state["te_claimed"] = list(data["te_claimed"])
    else:
        state["te_claimed"] = [te_numbers(e) for e in state["eggs_layed"]]
    return jsonify({"state": serialize(state), "stats": get_farm_stats(state)})

@app.route('/api/stats', methods=['POST'])
def api_stats():
    d = request.json.get("state", default_state())
    return jsonify(get_farm_stats(d))

@app.route('/api/action/wait', methods=['POST'])
def action_wait():
    data    = request.json
    d       = data["state"]
    mode    = data.get("mode", "offline")
    wtype   = data.get("wait_type", "time")
    value   = data.get("value", "1h")
    try:
        cli = dict_to_state(d)
        f   = cli.farm
        if wtype == "cash":
            target = egg_read(str(value))
            t = time_cash_away(cli, target, printout=False) if mode=="offline" else time_cash_active(cli, target, printout=False)
        else:
            t = read_time(str(value))
        if mode == "offline":
            wait_offline(cli, t, printout=False)
        else:
            wait_active(cli, t, printout=False)
        d = state_to_dict(cli, d)
        # log format: "wait 1h" or "waitactive 1h" or "wait 100B cash" — replayable
        if wtype == "cash":
            cmd = f"wait {value} cash" if mode == "offline" else f"waitactive {value} cash"
        else:
            cmd = "wait" if mode == "offline" else "waitactive"
        add_log(d, cmd, f"{_fmt_time(t)}")
        return jsonify({"state": serialize(d), "stats": get_farm_stats(d)})
    except Exception as e:
        import traceback; traceback.print_exc()
        return jsonify({"error": str(e)}), 400

@app.route('/api/action/simulate_egg', methods=['POST'])
def action_simulate_egg():
    data   = request.json
    d      = data["state"]
    target = data.get("egg", d["egg"])
    mode   = data.get("mode", "time")
    value  = data.get("value", "1h")
    try:
        cli = dict_to_state(d)
        # Build the value string the CLI expects: "5te" or "1h"
        if mode == "te":
            s = f"{int(value)}te"
        else:
            s = str(value)
        layed_before = cli.eggs_layed[virtue_egg_index[target]]
        cli_simulate_egg(cli, s, target, printout=False)
        layed_after  = cli.eggs_layed[virtue_egg_index[target]]
        d = state_to_dict(cli, d)
        # log format: "curiosity 1h" or "curiosity 5te" — directly replayable
        cmd_val = f"{int(value)}te" if mode == "te" else str(value)
        add_log(d, target, f"{cmd_val} → +{fmt(layed_after - layed_before)} eggs")
        return jsonify({"state": serialize(d), "stats": get_farm_stats(d)})
    except Exception as e:
        import traceback; traceback.print_exc()
        return jsonify({"error": str(e)}), 400

@app.route('/api/action/shift', methods=['POST'])
def action_shift():
    data    = request.json
    d       = data["state"]
    new_egg = data.get("egg")
    if new_egg not in virtue_egg_index:
        return jsonify({"error": "Invalid egg"}), 400
    if new_egg == d["egg"]:
        return jsonify({"state": serialize(d), "stats": get_farm_stats(d)})
    try:
        cli = dict_to_state(d)
        cli_shift(cli, new_egg, printout=False)
        d = state_to_dict(cli, d)
        add_log(d, f"shift {new_egg}", "")
        return jsonify({"state": serialize(d), "stats": get_farm_stats(d)})
    except Exception as e:
        import traceback; traceback.print_exc()
        return jsonify({"error": str(e)}), 400

@app.route('/api/action/buy', methods=['POST'])
def action_buy():
    data     = request.json
    d        = data["state"]
    buy_type = data.get("type")
    idx      = data.get("index", 0)
    try:
        cli = dict_to_state(d)
        ok  = False
        if buy_type == "cr":
            ok = buy_cr(cli, int(idx), printout=False)
        elif buy_type == "hab":
            ok = buy_hab(cli, int(idx), printout=False)
        elif buy_type == "vehicle":
            ok = buy_vehicle(cli, int(idx), printout=False)
        elif buy_type == "silo":
            ok = buy_silo(cli, printout=False)
        if not ok:
            return jsonify({"error": "Cannot buy — check egg, cash, or max level"}), 400
        d = state_to_dict(cli, d)
        # Log as replayable command: "buy cr 5", "buy hab 0", "buy vehicle 2", "buy silo"
        if buy_type == "silo":
            add_log(d, "buy silo", "")
        else:
            add_log(d, f"buy {buy_type} {idx}", "")
        return jsonify({"state": serialize(d), "stats": get_farm_stats(d)})
    except Exception as e:
        import traceback; traceback.print_exc()
        return jsonify({"error": str(e)}), 400

@app.route('/api/action/buy_all', methods=['POST'])
def action_buy_all():
    data = request.json
    d    = data["state"]
    try:
        cli = dict_to_state(d)
        buy_all(cli)
        d = state_to_dict(cli, d)
        add_log(d, "buyall", f"on {d['egg']}")
        return jsonify({"state": serialize(d), "stats": get_farm_stats(d)})
    except Exception as e:
        import traceback; traceback.print_exc()
        return jsonify({"error": str(e)}), 400

@app.route('/api/action/prestige', methods=['POST'])
def action_prestige():
    data = request.json
    d    = data["state"]
    start_egg = data.get("start_egg", "curiosity")
    if start_egg not in ["curiosity","kindness","resilience","humility","integrity"]:
        start_egg = "curiosity"
    try:
        cli        = dict_to_state(d)
        te_claimed = d.get("te_claimed", [0]*5)
        te_gained  = sum(
            max(0, te_numbers(e) - int(te_claimed[i]))
            for i, e in enumerate(cli.eggs_layed)
        )
        new_te     = int(d["te"]) + te_gained
        add_log(d, "prestige", f"+{te_gained} TE → total {new_te}")
        fresh = default_state()
        fresh["egg"]          = start_egg
        fresh["te"]           = new_te
        fresh["se"]           = d["se"]
        fresh["pe"]           = d["pe"]
        fresh["er"]           = d["er"]
        fresh["colleggtibles"]= d["colleggtibles"]
        fresh["artifact_set"] = d["artifact_set"]
        fresh["events"]       = d.get("events", fresh["events"])
        fresh["video_doubler"]= d.get("video_doubler", True)
        fresh["log"]          = d["log"]
        fresh["shifts"]       = int(d["shifts"])
        fresh["shifts_start"] = int(d["shifts"])
        fresh["te_claimed"]   = [te_numbers(e) for e in cli.eggs_layed]
        fresh["eggs_layed"]   = [float(e) for e in cli.eggs_layed]
        return jsonify({"state": serialize(fresh), "stats": get_farm_stats(fresh)})
    except Exception as e:
        import traceback; traceback.print_exc()
        return jsonify({"error": str(e)}), 400

@app.route('/api/action/set_artifact', methods=['POST'])
def action_set_artifact():
    """Set one artifact slot. Expects slot (a1-a4) and artifact dict."""
    data  = request.json
    d     = data["state"]
    slot  = data.get("slot")        # "a1" .. "a4"
    art_d = data.get("artifact", {})
    if slot not in ("a1","a2","a3","a4"):
        return jsonify({"error": "Invalid slot"}), 400
    try:
        new_art = build_artifact(art_d)
        # Replace just this slot
        aset_d  = copy.deepcopy(d["artifact_set"])
        def art_to_dict(a):
            return {"type": a.type, "level": int(a.level), "rarity": int(a.rarity),
                    "stones": [{"type": a.stone1.type, "level": int(a.stone1.level)},
                               {"type": a.stone2.type, "level": int(a.stone2.level)},
                               {"type": a.stone3.type, "level": int(a.stone3.level)}]}
        aset_d[slot] = art_to_dict(new_art)
        # Validate the whole set builds ok
        build_artifact_set(aset_d)
        d["artifact_set"] = aset_d
        _rl = {0:'C',1:'R',2:'E',3:'L'}.get(new_art.rarity,'?')
        # Build replayable command: "artifact a1 totem 4 L lunar 3 lunar 3"
        stone_parts = []
        for st in [new_art.stone1, new_art.stone2, new_art.stone3]:
            if st.type:
                stone_parts.append(f"{st.type} {st.level}")
        if new_art.type:
            cmd = f"artifact {slot} {new_art.type} {new_art.level} {_rl}"
            if stone_parts:
                cmd += " " + " ".join(stone_parts)
        else:
            cmd = f"artifact {slot} clear"
        add_log(d, cmd, "")
        return jsonify({"state": serialize(d), "stats": get_farm_stats(d)})
    except Exception as e:
        return jsonify({"error": str(e)}), 400

@app.route('/api/action/video_doubler', methods=['POST'])
def action_video_doubler():
    data = request.json
    d    = data["state"]
    d["video_doubler"] = not bool(d.get("video_doubler", True))
    return jsonify({"state": serialize(d), "stats": get_farm_stats(d)})

@app.route('/api/upgrade_costs', methods=['POST'])
def get_upgrade_costs():
    d = request.json.get("state", default_state())
    try:
        f = build_farm(d)
        # We need a CLI state for research_available
        cli = dict_to_state(d)
        research_count = sum(d["cr"])

        cr_list = []
        for i in range(56):
            if d["cr"][i] >= max_cr[i]: continue
            if not research_available(cli, i): continue
            cost = cr_prices[i][int(d["cr"][i])] * f.artf.cr_cost * (1-0.05*d["er"][7]) * f.coll_effect("waterballoon") * f.event("cr")
            cr_list.append({
                "index": i, "name": cr_names[i][1], "effect": cr_names[i][2],
                "level": int(d["cr"][i]), "max": int(max_cr[i]),
                "cost": fmt(cost), "cost_raw": float(cost), "tier": int(cr_names[i][0])
            })

        hab_list = []
        for i in range(4):
            lv = int(d["habs"][i])
            if lv >= 19:
                hab_list.append({"index": i, "level": lv, "maxed": True,
                                 "capacity": fmt(hab_capacities[lv])})
                continue
            same = sum(1 for j in range(4) if d["habs"][j] == lv+1)
            cost = hab_prices[lv][same] * (1-0.05*d["er"][5]) * f.coll_effect("flame") * f.event("hab")
            hab_list.append({
                "index": i, "level": lv, "maxed": False,
                "capacity": fmt(hab_capacities[lv]),
                "next_capacity": fmt(hab_capacities[lv+1]),
                "cost": fmt(cost), "cost_raw": float(cost)
            })

        veh_list = []
        max_veh_lv = 16 + int(d["cr"][50])  # mirrors farm.py: 16 + cr[50]
        for i in range(f.max_vehicle_number):
            vl = int(d["vehicles"][i])
            maxed = vl >= max_veh_lv
            if vl > 12:
                cost = vehicle_prices[12][min(vl-12,16)] * (1-0.05*d["er"][6]) * f.coll_effect("lithium") * f.event("veh")
            else:
                same = sum(1 for j in range(f.max_vehicle_number) if d["vehicles"][j] == vl+1)
                cost = vehicle_prices[vl][same] * (1-0.05*d["er"][6]) * f.coll_effect("lithium") * f.event("veh")
            veh_list.append({
                "index": i, "level": vl, "maxed": maxed,
                "capacity": fmt(vehicle_capacities[min(vl,21)]),
                "cost": fmt(cost) if not maxed else "maxed", "cost_raw": float(cost) if not maxed else 0
            })

        silo_info = {
            "count": int(d["silos"]), "maxed": d["silos"] >= 10,
            "cost": fmt(silo_price[d["silos"]]) if d["silos"] < 10 else "maxed"
        }

        # Next tier unlock info
        next_tier_in = None
        for bound in cr_bounds:
            if bound > research_count:
                next_tier_in = int(bound - research_count)
                break

        return jsonify({"cr": cr_list, "habs": hab_list, "vehicles": veh_list, "silo": silo_info,
                        "next_tier_in": next_tier_in})
    except Exception as e:
        import traceback; traceback.print_exc()
        return jsonify({"error": str(e)}), 400

@app.route('/api/metadata', methods=['GET'])
def get_metadata():
    return jsonify({
        "artifact_specs": artifact_specs,
        "stone_specs":    stone_specs,
        "virtue_eggs":    list(virtue_egg_index.keys()),
        "cr_names":       [[int(r[0]), r[1], r[2]] for r in cr_names],
        "max_cr":         [int(x) for x in max_cr],
        "cr_bounds":      [int(x) for x in cr_bounds],
    })

if __name__ == '__main__':
    app.run(debug=True, port=5000)
